### ISSUE TITLE
Filter selection

### ISSUE THREAD

**Issue by timvisee** [timvisee/i3lock-slick#4]
Make it possible to select what filters to use from the command line.

Possible filter configuration:  
`i3lock-slick --filter blur:sigma=3 --filter invert`

## Checklist
- [x] Determine a CLI syntax.
- [x] Ability to parse filters and their properties.
- [x] Parse filter values from the CLI, and select the proper filters and parameters.
- [x] Apply all selected filters.
- [x] Implement filter selection in the dotfile.
- [x] Document all supported filters.

## TODO
- [x] Choose a different property separator, possibly `;`. A `,` might give trouble with floats.
- [ ] Implement all filters available with the `image` library.
- [ ] Implement filter processing in the intent.

## Syntax
This defines the syntax that will be used for filter selection.

### CLI options
Flag aliases:
- `--filter [FILTERS...]`
- `-f [FILTERS...]`

### Filter syntax
A filter is selected by it's name. Options may be specified to further configure the behavior of the selected filter. If no options are given but the filter has options available, defaults are used.

Possible filter notations:
- `blur`
- `blur:sigma=3`
- `blur:sigma=3;other=true`
- `blur : sigma = 3`
